[2023-02-01T12:19:45.262+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:19:45.265+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:19:45.266+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:19:45.266+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:19:45.279+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:19:45.277+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:19:45.280+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:19:45.308+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.053 seconds
[2023-02-01T12:20:15.429+0000] {processor.py:153} INFO - Started process (PID=76) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:20:15.430+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:20:15.431+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:20:15.431+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:20:15.435+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:20:15.434+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:20:15.436+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:20:15.455+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.030 seconds
[2023-02-01T12:20:45.674+0000] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:20:45.674+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:20:45.676+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:20:45.675+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:20:45.681+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:20:45.680+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:20:45.681+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:20:45.713+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.042 seconds
[2023-02-01T12:21:15.858+0000] {processor.py:153} INFO - Started process (PID=143) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:21:15.859+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:21:15.860+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:21:15.860+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:21:15.865+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:21:15.864+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:21:15.865+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:21:15.893+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-01T12:21:46.028+0000] {processor.py:153} INFO - Started process (PID=171) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:21:46.029+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:21:46.030+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:21:46.029+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:21:46.033+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:21:46.032+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:21:46.033+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:21:46.063+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.040 seconds
[2023-02-01T12:22:16.202+0000] {processor.py:153} INFO - Started process (PID=211) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:22:16.203+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:22:16.204+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:22:16.204+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:22:16.207+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:22:16.206+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:22:16.208+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:22:16.236+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.037 seconds
[2023-02-01T12:22:46.376+0000] {processor.py:153} INFO - Started process (PID=238) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:22:46.376+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:22:46.377+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:22:46.377+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:22:46.382+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:22:46.381+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:22:46.382+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:22:46.411+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-01T12:23:16.540+0000] {processor.py:153} INFO - Started process (PID=277) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:23:16.541+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:23:16.543+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:23:16.542+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:23:16.547+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:23:16.546+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:23:16.548+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:23:16.578+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.041 seconds
[2023-02-01T12:23:31.649+0000] {processor.py:153} INFO - Started process (PID=291) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:23:31.650+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:23:31.652+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:23:31.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:23:31.658+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:23:31.657+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:23:31.659+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:23:31.676+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.030 seconds
[2023-02-01T12:24:01.814+0000] {processor.py:153} INFO - Started process (PID=325) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:24:01.815+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:24:01.816+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:24:01.816+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:24:01.821+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:24:01.820+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:24:01.821+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:24:01.853+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.041 seconds
[2023-02-01T12:24:31.981+0000] {processor.py:153} INFO - Started process (PID=357) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:24:31.983+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:24:31.984+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:24:31.984+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:24:31.989+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:24:31.988+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:24:31.990+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:24:32.007+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.031 seconds
[2023-02-01T12:25:02.162+0000] {processor.py:153} INFO - Started process (PID=397) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:25:02.163+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:25:02.165+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:25:02.165+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:25:02.169+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:25:02.168+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:25:02.171+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:25:02.188+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.029 seconds
[2023-02-01T12:25:32.329+0000] {processor.py:153} INFO - Started process (PID=424) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:25:32.330+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:25:32.331+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:25:32.331+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:25:32.335+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:25:32.334+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:25:32.335+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:25:32.351+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.025 seconds
[2023-02-01T12:26:02.489+0000] {processor.py:153} INFO - Started process (PID=465) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:26:02.490+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:26:02.491+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:26:02.491+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:26:02.497+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:26:02.495+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:26:02.497+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:26:02.520+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.037 seconds
[2023-02-01T12:26:32.644+0000] {processor.py:153} INFO - Started process (PID=492) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:26:32.645+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:26:32.646+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:26:32.645+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:26:32.649+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:26:32.648+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:26:32.650+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:26:32.678+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.038 seconds
[2023-02-01T12:27:02.832+0000] {processor.py:153} INFO - Started process (PID=532) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:27:02.833+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:27:02.834+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:27:02.834+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:27:02.839+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:27:02.838+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:27:02.839+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:27:02.867+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-01T12:27:32.988+0000] {processor.py:153} INFO - Started process (PID=559) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:27:32.990+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:27:32.991+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:27:32.991+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:27:32.997+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:27:32.994+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:27:32.998+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:27:33.018+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.034 seconds
[2023-02-01T12:28:03.159+0000] {processor.py:153} INFO - Started process (PID=600) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:28:03.159+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:28:03.161+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:28:03.161+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:28:03.165+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:28:03.164+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:28:03.166+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:28:03.194+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.038 seconds
[2023-02-01T12:28:33.321+0000] {processor.py:153} INFO - Started process (PID=629) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:28:33.322+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:28:33.324+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:28:33.324+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:28:33.328+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:28:33.327+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:28:33.329+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:28:33.356+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.038 seconds
[2023-02-01T12:29:03.484+0000] {processor.py:153} INFO - Started process (PID=669) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:29:03.487+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:29:03.488+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:29:03.488+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:29:03.491+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:29:03.490+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:29:03.492+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:29:03.520+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-01T12:29:33.651+0000] {processor.py:153} INFO - Started process (PID=696) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:29:33.652+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:29:33.653+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:29:33.653+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:29:33.657+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:29:33.656+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:29:33.657+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:29:33.675+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.027 seconds
[2023-02-01T12:30:03.837+0000] {processor.py:153} INFO - Started process (PID=736) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:30:03.838+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:30:03.839+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:30:03.839+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:30:03.843+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:30:03.842+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:30:03.843+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:30:03.862+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.028 seconds
[2023-02-01T12:30:34.006+0000] {processor.py:153} INFO - Started process (PID=763) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:30:34.008+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:30:34.009+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:30:34.009+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:30:34.013+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:30:34.012+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:30:34.014+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:30:34.041+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.041 seconds
[2023-02-01T12:31:04.190+0000] {processor.py:153} INFO - Started process (PID=803) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:31:04.190+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:31:04.192+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:31:04.192+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:31:04.196+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:31:04.195+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:31:04.196+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:31:04.223+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.037 seconds
[2023-02-01T12:31:34.337+0000] {processor.py:153} INFO - Started process (PID=830) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:31:34.338+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:31:34.339+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:31:34.339+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:31:34.344+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:31:34.343+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:31:34.345+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:31:34.366+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.034 seconds
[2023-02-01T12:32:04.481+0000] {processor.py:153} INFO - Started process (PID=869) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:32:04.482+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:32:04.483+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:32:04.483+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:32:04.488+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:32:04.486+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:32:04.489+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:32:04.516+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.040 seconds
[2023-02-01T12:32:34.660+0000] {processor.py:153} INFO - Started process (PID=906) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:32:34.660+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:32:34.662+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:32:34.662+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:32:34.666+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:32:34.665+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:32:34.666+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:32:34.696+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-01T12:33:04.818+0000] {processor.py:153} INFO - Started process (PID=937) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:33:04.819+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:33:04.820+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:33:04.820+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:33:04.824+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:33:04.823+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:33:04.824+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:33:04.844+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.030 seconds
[2023-02-01T12:33:35.015+0000] {processor.py:153} INFO - Started process (PID=977) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:33:35.016+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:33:35.017+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:33:35.017+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:33:35.023+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:33:35.022+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:33:35.023+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:33:35.052+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.042 seconds
[2023-02-01T12:34:05.193+0000] {processor.py:153} INFO - Started process (PID=1004) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:34:05.194+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:34:05.195+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:34:05.195+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:34:05.199+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:34:05.198+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:34:05.199+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:34:05.225+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.038 seconds
[2023-02-01T12:34:35.354+0000] {processor.py:153} INFO - Started process (PID=1044) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:34:35.355+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:34:35.357+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:34:35.357+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:34:35.360+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:34:35.359+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:34:35.361+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:34:35.388+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.038 seconds
[2023-02-01T12:35:05.542+0000] {processor.py:153} INFO - Started process (PID=1071) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:35:05.543+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:35:05.544+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:35:05.544+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:35:05.548+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:35:05.547+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:35:05.549+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:35:05.575+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.036 seconds
[2023-02-01T12:35:35.716+0000] {processor.py:153} INFO - Started process (PID=1111) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:35:35.717+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:35:35.719+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:35:35.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:35:35.723+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:35:35.722+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:35:35.723+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:35:35.751+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-01T12:36:05.887+0000] {processor.py:153} INFO - Started process (PID=1138) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:36:05.888+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:36:05.889+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:36:05.889+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:36:05.893+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:36:05.892+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:36:05.893+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:36:05.909+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.026 seconds
[2023-02-01T12:36:36.045+0000] {processor.py:153} INFO - Started process (PID=1180) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:36:36.046+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:36:36.048+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:36:36.047+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:36:36.052+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:36:36.051+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:36:36.052+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:36:36.080+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-01T12:37:06.208+0000] {processor.py:153} INFO - Started process (PID=1207) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:37:06.209+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:37:06.210+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:37:06.210+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:37:06.214+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:37:06.213+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:37:06.215+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:37:06.233+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.030 seconds
[2023-02-01T12:37:36.405+0000] {processor.py:153} INFO - Started process (PID=1246) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:37:36.406+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:37:36.407+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:37:36.406+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:37:36.411+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:37:36.410+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:37:36.411+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:37:36.441+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-01T12:38:06.563+0000] {processor.py:153} INFO - Started process (PID=1274) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:38:06.564+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:38:06.566+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:38:06.565+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:38:06.570+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:38:06.569+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:38:06.571+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:38:06.599+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-01T12:38:36.753+0000] {processor.py:153} INFO - Started process (PID=1315) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:38:36.754+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:38:36.755+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:38:36.755+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:38:36.760+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:38:36.759+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:38:36.761+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:38:36.789+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-01T12:39:06.923+0000] {processor.py:153} INFO - Started process (PID=1355) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:39:06.924+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:39:06.926+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:39:06.925+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:39:06.930+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:39:06.929+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:39:06.931+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:39:06.952+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.033 seconds
[2023-02-01T12:39:37.136+0000] {processor.py:153} INFO - Started process (PID=1382) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:39:37.136+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:39:37.138+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:39:37.138+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:39:37.141+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:39:37.140+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:39:37.142+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:39:37.168+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.035 seconds
[2023-02-01T12:40:07.312+0000] {processor.py:153} INFO - Started process (PID=1422) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:40:07.313+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:40:07.314+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:40:07.314+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:40:07.318+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:40:07.317+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:40:07.318+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:40:07.334+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.026 seconds
[2023-02-01T12:40:37.498+0000] {processor.py:153} INFO - Started process (PID=1449) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:40:37.498+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:40:37.499+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:40:37.499+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:40:37.503+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:40:37.502+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:40:37.503+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:40:37.531+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.037 seconds
[2023-02-01T12:41:07.678+0000] {processor.py:153} INFO - Started process (PID=1489) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:41:07.679+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:41:07.680+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:41:07.680+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:41:07.685+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:41:07.683+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:41:07.685+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:41:07.703+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.028 seconds
[2023-02-01T12:41:37.861+0000] {processor.py:153} INFO - Started process (PID=1516) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:41:37.862+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:41:37.864+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:41:37.864+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:41:37.868+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:41:37.867+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:41:37.868+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:41:37.916+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.058 seconds
[2023-02-01T12:42:08.063+0000] {processor.py:153} INFO - Started process (PID=1557) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:42:08.065+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:42:08.066+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:42:08.066+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:42:08.070+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:42:08.069+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:42:08.071+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:42:08.100+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.045 seconds
[2023-02-01T12:42:38.265+0000] {processor.py:153} INFO - Started process (PID=1597) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:42:38.266+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:42:38.267+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:42:38.267+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:42:38.270+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:42:38.269+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:42:38.270+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:42:38.286+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.025 seconds
[2023-02-01T12:43:08.447+0000] {processor.py:153} INFO - Started process (PID=1624) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:43:08.447+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:43:08.449+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:43:08.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:43:08.452+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:43:08.451+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:43:08.453+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:43:08.479+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.036 seconds
[2023-02-01T12:43:38.616+0000] {processor.py:153} INFO - Started process (PID=1664) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:43:38.617+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:43:38.618+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:43:38.618+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:43:38.622+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:43:38.621+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:43:38.623+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:43:38.650+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.038 seconds
[2023-02-01T12:44:08.801+0000] {processor.py:153} INFO - Started process (PID=1692) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:44:08.803+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:44:08.805+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:44:08.804+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:44:08.818+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:44:08.814+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:44:08.818+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:44:08.851+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.055 seconds
[2023-02-01T12:44:38.971+0000] {processor.py:153} INFO - Started process (PID=1732) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:44:38.972+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:44:38.974+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:44:38.973+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:44:38.978+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:44:38.977+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:44:38.978+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:44:39.005+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.036 seconds
[2023-02-01T12:45:09.205+0000] {processor.py:153} INFO - Started process (PID=1769) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:45:09.207+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:45:09.208+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:45:09.208+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:45:09.213+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:45:09.212+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:45:09.214+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:45:09.234+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.033 seconds
[2023-02-01T12:45:39.362+0000] {processor.py:153} INFO - Started process (PID=1802) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:45:39.363+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:45:39.365+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:45:39.364+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:45:39.368+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:45:39.367+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:45:39.369+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:45:39.395+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.035 seconds
[2023-02-01T12:46:09.537+0000] {processor.py:153} INFO - Started process (PID=1843) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:46:09.538+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:46:09.539+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:46:09.539+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:46:09.543+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:46:09.542+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:46:09.543+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:46:09.559+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.024 seconds
[2023-02-01T12:46:39.726+0000] {processor.py:153} INFO - Started process (PID=1870) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:46:39.727+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:46:39.727+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:46:39.727+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:46:39.731+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:46:39.730+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:46:39.732+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:46:39.758+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.036 seconds
[2023-02-01T12:47:09.899+0000] {processor.py:153} INFO - Started process (PID=1910) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:47:09.900+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T12:47:09.902+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:47:09.902+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:47:09.906+0000] {logging_mixin.py:137} INFO - [2023-02-01T12:47:09.905+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T12:47:09.907+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T12:47:09.933+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-01T17:19:34.075+0000] {processor.py:153} INFO - Started process (PID=46) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:19:34.077+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:19:34.078+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:19:34.078+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:19:34.083+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:19:34.081+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:19:34.083+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:19:34.108+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-01T17:20:05.098+0000] {processor.py:153} INFO - Started process (PID=74) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:20:05.099+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:20:05.100+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:20:05.100+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:20:05.104+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:20:05.103+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:20:05.105+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:20:05.122+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.028 seconds
[2023-02-01T17:20:35.222+0000] {processor.py:153} INFO - Started process (PID=115) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:20:35.223+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:20:35.224+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:20:35.224+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:20:35.229+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:20:35.228+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:20:35.229+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:20:35.257+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-01T17:21:05.467+0000] {processor.py:153} INFO - Started process (PID=142) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:21:05.468+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:21:05.470+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:21:05.470+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:21:05.474+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:21:05.473+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:21:05.474+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:21:05.500+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.041 seconds
[2023-02-01T17:21:35.654+0000] {processor.py:153} INFO - Started process (PID=182) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:21:35.655+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:21:35.656+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:21:35.656+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:21:35.661+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:21:35.660+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:21:35.661+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:21:35.689+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.038 seconds
[2023-02-01T17:22:05.842+0000] {processor.py:153} INFO - Started process (PID=209) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:22:05.844+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:22:05.846+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:22:05.845+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:22:05.851+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:22:05.849+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:22:05.852+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:22:05.887+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.051 seconds
[2023-02-01T17:22:36.056+0000] {processor.py:153} INFO - Started process (PID=249) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:22:36.057+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:22:36.059+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:22:36.058+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:22:36.062+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:22:36.061+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:22:36.063+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:22:36.092+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-01T17:23:06.213+0000] {processor.py:153} INFO - Started process (PID=276) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:23:06.214+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:23:06.215+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:23:06.215+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:23:06.220+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:23:06.219+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:23:06.220+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:23:06.240+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.032 seconds
[2023-02-01T17:23:36.400+0000] {processor.py:153} INFO - Started process (PID=316) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:23:36.401+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:23:36.402+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:23:36.402+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:23:36.406+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:23:36.406+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:23:36.407+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:23:36.434+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.038 seconds
[2023-02-01T17:24:06.561+0000] {processor.py:153} INFO - Started process (PID=355) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:24:06.563+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:24:06.564+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:24:06.564+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:24:06.570+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:24:06.568+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:24:06.571+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:24:06.603+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.046 seconds
[2023-02-01T17:24:36.733+0000] {processor.py:153} INFO - Started process (PID=382) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:24:36.735+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:24:36.736+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:24:36.735+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:24:36.741+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:24:36.739+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:24:36.742+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:24:36.772+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.046 seconds
[2023-02-01T17:25:06.908+0000] {processor.py:153} INFO - Started process (PID=422) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:25:06.909+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:25:06.910+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:25:06.910+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:25:06.915+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:25:06.914+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:25:06.915+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:25:06.957+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.052 seconds
[2023-02-01T17:25:37.078+0000] {processor.py:153} INFO - Started process (PID=449) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:25:37.080+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:25:37.083+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:25:37.083+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:25:37.089+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:25:37.086+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:25:37.090+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:25:37.148+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.077 seconds
[2023-02-01T17:26:07.260+0000] {processor.py:153} INFO - Started process (PID=489) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:26:07.263+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:26:07.265+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:26:07.265+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:26:07.271+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:26:07.270+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:26:07.272+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:26:07.289+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.036 seconds
[2023-02-01T17:26:37.427+0000] {processor.py:153} INFO - Started process (PID=516) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:26:37.427+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:26:37.429+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:26:37.428+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:26:37.434+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:26:37.432+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:26:37.434+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:26:37.454+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.031 seconds
[2023-02-01T17:27:07.574+0000] {processor.py:153} INFO - Started process (PID=556) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:27:07.582+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-01T17:27:07.584+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:27:07.584+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:27:07.589+0000] {logging_mixin.py:137} INFO - [2023-02-01T17:27:07.588+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-01T17:27:07.590+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-01T17:27:07.611+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.044 seconds
