[2023-02-12T03:54:54.925+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:54:54.931+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T03:54:54.934+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:54:54.934+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:54:54.948+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:54:54.945+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T03:54:54.949+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:54:54.970+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.053 seconds
[2023-02-12T03:55:25.089+0000] {processor.py:153} INFO - Started process (PID=75) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:55:25.090+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T03:55:25.091+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:55:25.091+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:55:25.095+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:55:25.094+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T03:55:25.096+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:55:25.112+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.027 seconds
[2023-02-12T03:55:55.256+0000] {processor.py:153} INFO - Started process (PID=101) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:55:55.256+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T03:55:55.257+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:55:55.257+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:55:55.262+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:55:55.261+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T03:55:55.262+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:55:55.288+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.037 seconds
[2023-02-12T03:56:25.421+0000] {processor.py:153} INFO - Started process (PID=141) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:56:25.422+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T03:56:25.424+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:56:25.423+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:56:25.427+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:56:25.426+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T03:56:25.428+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:56:25.453+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.035 seconds
[2023-02-12T03:56:55.583+0000] {processor.py:153} INFO - Started process (PID=178) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:56:55.584+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T03:56:55.585+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:56:55.585+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:56:55.588+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:56:55.588+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T03:56:55.589+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:56:55.614+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.034 seconds
[2023-02-12T03:57:25.748+0000] {processor.py:153} INFO - Started process (PID=209) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:57:25.749+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T03:57:25.749+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:57:25.749+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:57:25.753+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:57:25.752+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T03:57:25.753+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:57:25.780+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.035 seconds
[2023-02-12T03:57:55.916+0000] {processor.py:153} INFO - Started process (PID=249) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:57:55.917+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T03:57:55.918+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:57:55.918+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:57:55.923+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:57:55.922+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T03:57:55.924+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:57:55.940+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.027 seconds
[2023-02-12T03:58:26.079+0000] {processor.py:153} INFO - Started process (PID=276) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:58:26.080+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T03:58:26.082+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:58:26.081+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:58:26.087+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:58:26.086+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T03:58:26.088+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:58:26.102+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.027 seconds
[2023-02-12T03:58:56.240+0000] {processor.py:153} INFO - Started process (PID=317) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:58:56.241+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T03:58:56.242+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:58:56.242+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:58:56.247+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:58:56.245+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T03:58:56.247+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:58:56.275+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.038 seconds
[2023-02-12T03:59:26.398+0000] {processor.py:153} INFO - Started process (PID=344) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:59:26.399+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T03:59:26.400+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:59:26.400+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:59:26.405+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:59:26.404+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T03:59:26.405+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:59:26.431+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.038 seconds
[2023-02-12T03:59:56.575+0000] {processor.py:153} INFO - Started process (PID=384) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:59:56.576+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T03:59:56.577+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:59:56.576+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:59:56.580+0000] {logging_mixin.py:137} INFO - [2023-02-12T03:59:56.579+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T03:59:56.581+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T03:59:56.606+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.034 seconds
[2023-02-12T04:00:26.734+0000] {processor.py:153} INFO - Started process (PID=421) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:00:26.735+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:00:26.736+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:00:26.736+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:00:26.740+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:00:26.739+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:00:26.740+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:00:26.769+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-12T04:00:56.932+0000] {processor.py:153} INFO - Started process (PID=452) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:00:56.933+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:00:56.936+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:00:56.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:00:56.939+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:00:56.938+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:00:56.940+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:00:56.954+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.027 seconds
[2023-02-12T04:01:27.093+0000] {processor.py:153} INFO - Started process (PID=492) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:01:27.105+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:01:27.107+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:01:27.107+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:01:27.114+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:01:27.113+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:01:27.114+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:01:27.129+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-12T04:01:57.241+0000] {processor.py:153} INFO - Started process (PID=519) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:01:57.242+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:01:57.243+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:01:57.243+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:01:57.248+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:01:57.247+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:01:57.249+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:01:57.274+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.037 seconds
[2023-02-12T04:02:27.415+0000] {processor.py:153} INFO - Started process (PID=558) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:02:27.416+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:02:27.417+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:02:27.417+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:02:27.420+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:02:27.419+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:02:27.420+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:02:27.446+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.035 seconds
[2023-02-12T04:02:57.571+0000] {processor.py:153} INFO - Started process (PID=595) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:02:57.572+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:02:57.573+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:02:57.573+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:02:57.577+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:02:57.576+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:02:57.578+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:02:57.596+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.028 seconds
[2023-02-12T04:03:27.707+0000] {processor.py:153} INFO - Started process (PID=626) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:03:27.708+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:03:27.709+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:03:27.709+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:03:27.715+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:03:27.714+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:03:27.716+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:03:27.736+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.033 seconds
[2023-02-12T04:03:57.828+0000] {processor.py:153} INFO - Started process (PID=660) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:03:57.829+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:03:57.831+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:03:57.830+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:03:57.836+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:03:57.834+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:03:57.836+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:03:57.860+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.037 seconds
[2023-02-12T04:04:27.974+0000] {processor.py:153} INFO - Started process (PID=693) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:04:27.975+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:04:27.976+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:04:27.975+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:04:27.980+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:04:27.979+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:04:27.981+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:04:28.010+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.040 seconds
[2023-02-12T04:04:58.136+0000] {processor.py:153} INFO - Started process (PID=720) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:04:58.136+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:04:58.138+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:04:58.138+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:04:58.142+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:04:58.141+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:04:58.143+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:04:58.170+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.038 seconds
[2023-02-12T04:05:28.299+0000] {processor.py:153} INFO - Started process (PID=759) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:05:28.300+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:05:28.301+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:05:28.301+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:05:28.305+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:05:28.304+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:05:28.305+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:05:28.330+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.034 seconds
[2023-02-12T04:05:58.480+0000] {processor.py:153} INFO - Started process (PID=799) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:05:58.481+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:05:58.482+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:05:58.482+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:05:58.486+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:05:58.485+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:05:58.487+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:05:58.512+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.036 seconds
[2023-02-12T04:06:28.649+0000] {processor.py:153} INFO - Started process (PID=826) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:06:28.651+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:06:28.652+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:06:28.652+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:06:28.655+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:06:28.654+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:06:28.656+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:06:28.673+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.028 seconds
[2023-02-12T04:06:58.826+0000] {processor.py:153} INFO - Started process (PID=866) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:06:58.827+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:06:58.829+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:06:58.829+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:06:58.832+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:06:58.831+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:06:58.832+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:06:58.859+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.037 seconds
[2023-02-12T04:07:28.997+0000] {processor.py:153} INFO - Started process (PID=892) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:07:28.998+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:07:28.999+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:07:28.999+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:07:29.003+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:07:29.001+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:07:29.003+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:07:29.028+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.034 seconds
[2023-02-12T04:07:59.134+0000] {processor.py:153} INFO - Started process (PID=933) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:07:59.136+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:07:59.137+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:07:59.137+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:07:59.141+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:07:59.140+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:07:59.141+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:07:59.170+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.041 seconds
[2023-02-12T04:08:29.309+0000] {processor.py:153} INFO - Started process (PID=969) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:08:29.310+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:08:29.311+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:08:29.311+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:08:29.317+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:08:29.315+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:08:29.318+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:08:29.353+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.049 seconds
[2023-02-12T04:08:59.497+0000] {processor.py:153} INFO - Started process (PID=1000) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:08:59.498+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:08:59.500+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:08:59.499+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:08:59.504+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:08:59.503+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:08:59.504+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:08:59.530+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.040 seconds
[2023-02-12T04:09:29.666+0000] {processor.py:153} INFO - Started process (PID=1040) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:09:29.668+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:09:29.669+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:09:29.668+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:09:29.673+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:09:29.672+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:09:29.673+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:09:29.699+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.036 seconds
[2023-02-12T04:09:59.860+0000] {processor.py:153} INFO - Started process (PID=1067) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:09:59.861+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:09:59.862+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:09:59.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:09:59.866+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:09:59.865+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:09:59.867+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:09:59.892+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.036 seconds
[2023-02-12T04:10:30.045+0000] {processor.py:153} INFO - Started process (PID=1108) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:10:30.046+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:10:30.047+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:10:30.047+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:10:30.051+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:10:30.050+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:10:30.051+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:10:30.067+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.031 seconds
[2023-02-12T04:11:00.243+0000] {processor.py:153} INFO - Started process (PID=1135) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:11:00.244+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:11:00.245+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:11:00.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:11:00.249+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:11:00.248+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:11:00.250+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:11:00.265+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.026 seconds
[2023-02-12T04:11:30.364+0000] {processor.py:153} INFO - Started process (PID=1176) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:11:30.365+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:11:30.367+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:11:30.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:11:30.372+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:11:30.370+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:11:30.372+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:11:30.405+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.045 seconds
[2023-02-12T04:12:00.479+0000] {processor.py:153} INFO - Started process (PID=1203) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:12:00.480+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:12:00.481+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:12:00.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:12:00.486+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:12:00.484+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:12:00.486+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:12:00.515+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.039 seconds
[2023-02-12T04:12:30.616+0000] {processor.py:153} INFO - Started process (PID=1243) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:12:30.617+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:12:30.618+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:12:30.618+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:12:30.622+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:12:30.621+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:12:30.622+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:12:30.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.043 seconds
[2023-02-12T04:13:00.745+0000] {processor.py:153} INFO - Started process (PID=1270) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:13:00.746+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:13:00.748+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:13:00.748+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:13:00.753+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:13:00.751+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:13:00.753+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:13:00.783+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.041 seconds
[2023-02-12T04:13:30.873+0000] {processor.py:153} INFO - Started process (PID=1310) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:13:30.874+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:13:30.875+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:13:30.875+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:13:30.879+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:13:30.878+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:13:30.880+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:13:30.909+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.040 seconds
[2023-02-12T04:14:01.037+0000] {processor.py:153} INFO - Started process (PID=1336) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:14:01.038+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:14:01.040+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:14:01.039+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:14:01.044+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:14:01.043+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:14:01.045+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:14:01.067+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.032 seconds
[2023-02-12T04:14:31.191+0000] {processor.py:153} INFO - Started process (PID=1376) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:14:31.192+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:14:31.193+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:14:31.193+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:14:31.199+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:14:31.197+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:14:31.199+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:14:31.226+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.041 seconds
[2023-02-12T04:15:01.330+0000] {processor.py:153} INFO - Started process (PID=1403) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:15:01.331+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:15:01.333+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:15:01.332+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:15:01.343+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:15:01.342+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:15:01.344+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:15:01.364+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.038 seconds
[2023-02-12T04:15:31.462+0000] {processor.py:153} INFO - Started process (PID=1437) to work on /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:15:31.463+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_airbyte_example.py for tasks to queue
[2023-02-12T04:15:31.464+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:15:31.464+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:15:31.469+0000] {logging_mixin.py:137} INFO - [2023-02-12T04:15:31.468+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_example.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-12T04:15:31.470+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_example.py
[2023-02-12T04:15:31.491+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_airbyte_example.py took 0.033 seconds
